#!/usr/bin/env bash

# Run lintball using Docker on git commit

set -eu

LINTBALL_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

if [[ ! -f "${LINTBALL_DIR}/lintballrc-defaults.json" ]]; then
  # This is lintball itself
  "${LINTBALL_DIR}"/scripts/build-local-docker-image.sh
  docker run --rm -v "${PWD}:/workspace" lintball:local lintball pre-commit
else
  docker run --rm -v "${PWD}:/workspace" elijahru/lintball:latest lintball pre-commit
fi
