#!/usr/bin/env bash

# Run lintball using Docker on git commit

set -eu

parent_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

if [[ -f "${parent_dir}/configs/lintballrc-defaults.json" ]]; then
  # This is lintball itself
  "${parent_dir}"/scripts/build-local-docker-image.sh
  docker run --rm -v "${parent_dir}:/workspace" lintball:local lintball pre-commit
else
  if [[ -z ${GIT_DIR:-} ]]; then
    echo "Error: Not a git repository."
    exit 1
  fi

  workspace=$(git rev-parse --show-toplevel)
  docker run --rm -v "${workspace}:/workspace" elijahru/lintball:latest lintball pre-commit
fi
