name: CI Workflow

on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run lintball
        uses: ./

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: ./scripts/run-tests-external.sh

  build-and-push-docker-images:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    environment: "Lintball environment"
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        run: ./scripts/build-and-push-docker-images.bash

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    environment: "Lintball environment"
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-and-push-docker-images]
    steps:
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
